version: '3'

services:
  backend:
    build: ./
    container_name: nestjs_api_devops
    ports:
      - '3000:3000'
    networks:
      - nestjs_network

networks:
  nestjs_network:
    driver: bridge