name: Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    env:
      name: ${{ github.ref_name }}
      url: http://3.79.229.70:3000
    steps:
      - id: deploy
        name: Deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v0.5.7
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: eu-central-1
          app_port: 3000


